# Generated by Django 5.1 on 2026-01-13 23:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('horario', models.TimeField(default=django.utils.timezone.now)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto para Inscrição'), ('RESERVADO', 'Reservado/Lotado'), ('FINALIZADO', 'Evento Finalizado')], default='ABERTO', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.CharField(max_length=100)),
                ('foto', models.ImageField(upload_to='membros_fotos/')),
            ],
        ),
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo_arquivo', models.CharField(choices=[('IMAGEM', 'Imagem'), ('VIDEO', 'Vídeo')], default='IMAGEM', max_length=6)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='midia_arquivos/')),
                ('url_video', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem_capa', models.ImageField(upload_to='projetos_capas/')),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('CONCLUIDO', 'Concluído'), ('ARQUIVADO', 'Arquivado')], default='ATIVO', max_length=10)),
            ],
        ),
    ]
