# Generated by Django 5.1 on 2026-01-16 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Membro',
        ),
        migrations.DeleteModel(
            name='Midia',
        ),
        migrations.DeleteModel(
            name='Projeto',
        ),
    ]
